version: "3"

services:
  api:
    image: player-session-service
    container_name: api
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
    - ../.env
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "5001:5000"
    command: '/bin/bash -c "sleep 20 && python3 /usr/src/app/player-session-service/index.py"'

  cassandra:
    image: cassandra_dsbulk
    container_name: cassandra
    build:
      context: .
      dockerfile: DockerFileCassandra
    ports:
      - '9042:9042'
    volumes:
      - "./assignment_data.jsonl:/assignment_data.json"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
    - "./keyspace.cql:/keyspace.cql"
    -  "./schema.cql:/schema.cql"
    command: '/bin/bash -c "echo loading cassandra keyspace and tables && cqlsh cassandra -f /keyspace.cql && cqlsh cassandra -f /schema.cql"'

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"